version: "3"
tasks:
  lint:
    desc: run all linters
    cmds:
      - selene .
      - stylua --check .

  format:
    desc: run formatter
    cmd: stylua .

  test:
    desc: run all tests
    cmds:
      - |
        nvim --clean --headless \
             -u ./scripts/minimal_init.lua \
             -c "lua MiniTest.run()" \
             -c ":qa!"

  docgen:
    desc: generate vimhelp
    cmds:
      - |
        nvim --clean --headless \
             -u "./scripts/minimal_init.lua" \
             -c "luafile ./scripts/docgen.lua" \
             -c ":qa!"
