version: "3"
tasks:
  format:
    desc: formats all lua files in repo
    cmds:
      - stylua .

  lint:
    desc: runs all linters
    cmds:
      - task: selene
      - task: stylua:check

  selene:
    desc: runs lua linter(selene)
    cmds:
      - selene .

  stylua:check:
    desc: runs stylua in check mode
    cmds:
      - stylua --check .

  stylua:
    desc: runs lua formatter
    cmds:
      - stylua .

  tests:
    desc: run all tests
    cmds:
      - |
        nvim --clean --headless \
             -u ./scripts/minimal_init.lua \
             +"lua MiniTest.run()"

  ci:install-deps:
    desc: install dependencies for CI
    cmds: ['nvim --headless -u "./scripts/minimal_init.lua" -c "GoInstallDeps" -c "qa!"']

  docgen:
    desc: generate vimhelp
    cmds:
      - |
        nvim --clean  --headless \
             -u "./scripts/minimal_init.lua" \
             +"luafile ./scripts/docgen.lua" \
             +":qa!"
