version: "3"
tasks:
  lint:
    cmds:
      - selene .
      - stylua --check .

  format:
    cmd: stylua .

  test:
    cmds:
      - |
        nvim --clean --headless \
             -u ./scripts/minimal_init.lua \
             -c "lua MiniTest.run()" \
             -c ":qa!"

  docgen:
    desc: generate vimhelp
    cmds:
      - |
        nvim --clean --headless \
             -u "./scripts/minimal_init.lua" \
             -c "luafile ./scripts/docgen.lua" \
             -c ":qa!"

  install-deps:
    desc: installs go bin (used in CI)
    cmds:
      - |
        nvim --clean --headless \
             -u "./scripts/minimal_init.lua" \
             +GoInstallDepsSync +qa
