version: "3"
tasks:
  format:
    desc: formats all lua files in repo
    cmds: [stylua .]

  lint:
    desc: runs all linters
    cmds:
      - task: lint_selene
      - task: lint_stylua

  lint_selene:
    desc: runs lua linter(selene)
    cmds: [selene .]

  lint_stylua:
    desc: runs stylua in check mode
    cmds: [stylua --check .]

  test:
    desc: runs all tests
    aliases: [tests, spec]
    cmds:
      - |
        nvim --headless \
          -u ./scripts/minimal_init.lua\
          -c "PlenaryBustedDirectory spec \
              {minimal_init='./scripts/minimal_init.lua'\
              ,sequential=true}"
