version: "3"
tasks:
  lint:
    desc: runs all linters
    cmds:
      - task: selene
      - stylua --check .

  selene:
    desc: runs lua linter(selene)
    cmds:
      - selene .

  stylua:
    desc: runs lua formatter
    cmds:
      - stylua .

  tests:
    desc: run all tests
    cmds:
      - |
        nvim --clean --headless \
             -u ./scripts/minimal_init.lua \
             -c "lua MiniTest.run()"

  docgen:
    desc: generate vimhelp
    cmds:
      - |
        nvim --clean --headless \
             -u "./scripts/minimal_init.lua" \
             -c "luafile ./scripts/docgen.lua" \
             -c ":qa!"
