Output new.gif
Require nvim

Set FontFamily "JetBrains Mono"
Set Height 800
Set Width 1500
Set Padding 20
Set Shell "bash"
Set Theme "tokyonight"
Set TypingSpeed 250ms

Hide Type@0ms "./nvim.sh new.go" Enter Show

Type@400ms "jjjjjjjzz"
Type ":GoNew" Sleep 500ms Enter
Sleep 1s

Type "/Gene" Enter Type@0ms "zz"
Type ":GoNew" Sleep 500ms Enter
Sleep 1s

Type "/Embed" Enter Type@0ms "zz"
Type ":GoNew" Sleep 500ms Enter
Sleep 1s

Sleep 5s
