version: "3"
tasks:
  generate:
    deps:
      - comment
      - iferr
      - tags
      - impl

  comment:
    cmd: vhs comment.tape

  iferr:
    cmd: vhs iferr.tape

  tags:
    cmd: vhs tags.tape

  impl:
    cmd: vhs impl.tape
